#!/usr/bin/env bash
# Cloud Agent install step for the bookmate (Hasel) Astro app.
# Idempotent: safe to run multiple times and against cached state.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

corepack enable >/dev/null 2>&1 || true

pnpm install --frozen-lockfile

# Astro/Vite loads env by mode; `astro dev` reads `.env.development`.
# It is gitignored, so materialize a DEV file pointing at the public aoxdev
# ORDS endpoints when one is not already present. No secrets are written here.
if [ ! -f .env.development ]; then
  cat > .env.development <<'EOF'
# Auto-generated by .cursor/install.sh for Cloud Agent DEV. Edit as needed.
ORDS_API_BASE_URL=https://g9549f707e8ebfa-aoxdevelop.adb.sa-saopaulo-1.oraclecloudapps.com/ords/aoxdev/api/v1/
ORDS_PUBLIC_API_BASE_URL=https://g9549f707e8ebfa-aoxdevelop.adb.sa-saopaulo-1.oraclecloudapps.com/ords/aoxdev/public/v1/
ORDS_AI_BASE_URL=https://g9549f707e8ebfa-aoxdevelop.adb.sa-saopaulo-1.oraclecloudapps.com/ords/aoxdev/ai/

PUBLIC_BOOKMATE_PUBLIC_DOMAIN=http://localhost:4321
PUBLIC_BOOKMATE_PROFILE_PLACEHOLDER_IMAGE_URL=https://placehold.co/200x200?text=Bookmate
PUBLIC_G_MAPS_API_KEY=
PUBLIC_FIREBASE_API_KEY=
PUBLIC_FIREBASE_AUTH_DOMAIN=
PUBLIC_FIREBASE_PROJECT_ID=
PUBLIC_FIREBASE_STORAGE_BUCKET=
PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
PUBLIC_FIREBASE_APP_ID=
PUBLIC_FIREBASE_MEASUREMENT_ID=
PUBLIC_FIREBASE_VAPID_KEY=

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:4321/api/google/callback

ESIGN_API_BASE_URL=https://api-staging.etick.uno
ESIGN_API_KEY=sk_test_placeholder
ESIGN_CALLBACK_SERVICE_TOKEN=
CRON_SECRET=

PUBLIC_STADIA_MAPS_KEY=
PUBLIC_ODONTOGRAM_GLB_URL=https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/gr7djv0kcgrr/b/bucket-hasel-aoxdev/o/odontograma%2Fboca.glb
EOF
  echo "[install] created .env.development"
else
  echo "[install] .env.development already present, leaving as-is"
fi
